[package]
name = "pigpio"
version = "0.1.0"
authors = ["Sergey Shepelev <temotor@gmail.com>"]
license = "Unlicense"
edition = "2018"

[target.'cfg(target_os="linux")'.dependencies]
pigpio-sys = { path = "../pigpio-sys" }
