// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iodin.proto

package iodin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request_Command int32

const (
	Request_INVALID   Request_Command = 0
	Request_MDB_OPEN  Request_Command = 1
	Request_MDB_RESET Request_Command = 2
	Request_MDB_TX    Request_Command = 3
)

var Request_Command_name = map[int32]string{
	0: "INVALID",
	1: "MDB_OPEN",
	2: "MDB_RESET",
	3: "MDB_TX",
}
var Request_Command_value = map[string]int32{
	"INVALID":   0,
	"MDB_OPEN":  1,
	"MDB_RESET": 2,
	"MDB_TX":    3,
}

func (x Request_Command) String() string {
	return proto.EnumName(Request_Command_name, int32(x))
}
func (Request_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iodin_a5efde40e0341dee, []int{0, 0}
}

type Response_Status int32

const (
	Response_INVALID      Response_Status = 0
	Response_OK           Response_Status = 1
	Response_ERR_INPUT    Response_Status = 2
	Response_ERR_INTERNAL Response_Status = 3
	Response_ERR_CHECKSUM Response_Status = 4
	Response_ERR_TIMEOUT  Response_Status = 5
	Response_ERR_HARDWARE Response_Status = 6
)

var Response_Status_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "ERR_INPUT",
	3: "ERR_INTERNAL",
	4: "ERR_CHECKSUM",
	5: "ERR_TIMEOUT",
	6: "ERR_HARDWARE",
}
var Response_Status_value = map[string]int32{
	"INVALID":      0,
	"OK":           1,
	"ERR_INPUT":    2,
	"ERR_INTERNAL": 3,
	"ERR_CHECKSUM": 4,
	"ERR_TIMEOUT":  5,
	"ERR_HARDWARE": 6,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_iodin_a5efde40e0341dee, []int{1, 0}
}

type Request struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Command              Request_Command `protobuf:"varint,2,opt,name=command,proto3,enum=iodin.Request_Command" json:"command,omitempty"`
	Timeout              uint32          `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	ArgUint              uint32          `protobuf:"varint,4,opt,name=arg_uint,json=argUint,proto3" json:"arg_uint,omitempty"`
	ArgBytes             []byte          `protobuf:"bytes,5,opt,name=arg_bytes,json=argBytes,proto3" json:"arg_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_iodin_a5efde40e0341dee, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Request) GetCommand() Request_Command {
	if m != nil {
		return m.Command
	}
	return Request_INVALID
}

func (m *Request) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Request) GetArgUint() uint32 {
	if m != nil {
		return m.ArgUint
	}
	return 0
}

func (m *Request) GetArgBytes() []byte {
	if m != nil {
		return m.ArgBytes
	}
	return nil
}

type Response struct {
	Version              uint32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status               Response_Status `protobuf:"varint,2,opt,name=status,proto3,enum=iodin.Response_Status" json:"status,omitempty"`
	Error                string          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DataBytes            []byte          `protobuf:"bytes,4,opt,name=data_bytes,json=dataBytes,proto3" json:"data_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_iodin_a5efde40e0341dee, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_INVALID
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetDataBytes() []byte {
	if m != nil {
		return m.DataBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "iodin.Request")
	proto.RegisterType((*Response)(nil), "iodin.Response")
	proto.RegisterEnum("iodin.Request_Command", Request_Command_name, Request_Command_value)
	proto.RegisterEnum("iodin.Response_Status", Response_Status_name, Response_Status_value)
}

func init() { proto.RegisterFile("iodin.proto", fileDescriptor_iodin_a5efde40e0341dee) }

var fileDescriptor_iodin_a5efde40e0341dee = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x6a, 0xf2, 0x30,
	0x18, 0x86, 0xff, 0xaa, 0x6d, 0xed, 0xa7, 0xfe, 0x0b, 0x61, 0x8c, 0x8e, 0x31, 0x10, 0x8f, 0x3c,
	0x2a, 0x63, 0xbb, 0x80, 0x51, 0x35, 0x60, 0x51, 0xab, 0xc4, 0x76, 0xdb, 0x99, 0xd4, 0x19, 0xa4,
	0x07, 0x36, 0x2e, 0x49, 0x07, 0xbb, 0xe3, 0x5d, 0xc5, 0x18, 0x69, 0xda, 0x83, 0x31, 0xd8, 0xe1,
	0xf3, 0xbd, 0x6f, 0xde, 0xf2, 0x50, 0xe8, 0xe5, 0xfc, 0x90, 0x17, 0xc1, 0x59, 0x70, 0xc5, 0xb1,
	0x5d, 0xc1, 0xe8, 0xd3, 0x02, 0x97, 0xb2, 0xb7, 0x92, 0x49, 0x85, 0x7d, 0x70, 0xdf, 0x99, 0x90,
	0x39, 0x2f, 0x7c, 0x6b, 0x68, 0x8d, 0x07, 0xb4, 0x41, 0x7c, 0x07, 0xee, 0x2b, 0x3f, 0x9d, 0xb2,
	0xe2, 0xe0, 0xb7, 0x86, 0xd6, 0xf8, 0xff, 0xfd, 0x55, 0x60, 0xb6, 0xea, 0xa7, 0xc1, 0xd4, 0xa4,
	0xb4, 0xa9, 0xe9, 0x2d, 0x95, 0x9f, 0x18, 0x2f, 0x95, 0xdf, 0x36, 0x5b, 0x35, 0xe2, 0x6b, 0xe8,
	0x66, 0xe2, 0xb8, 0x2b, 0xf3, 0x42, 0xf9, 0x1d, 0x13, 0x65, 0xe2, 0x98, 0xe6, 0x85, 0xc2, 0x37,
	0xe0, 0xe9, 0x68, 0xff, 0xa1, 0x98, 0xf4, 0xed, 0xa1, 0x35, 0xee, 0x53, 0xdd, 0x9d, 0x68, 0x1e,
	0x3d, 0x82, 0x5b, 0x7f, 0x05, 0xf7, 0xc0, 0x8d, 0xe2, 0xa7, 0x70, 0x19, 0xcd, 0xd0, 0x3f, 0xdc,
	0x87, 0xee, 0x6a, 0x36, 0xd9, 0xad, 0x37, 0x24, 0x46, 0x16, 0x1e, 0x80, 0xa7, 0x89, 0x92, 0x2d,
	0x49, 0x50, 0x0b, 0x03, 0x38, 0x1a, 0x93, 0x17, 0xd4, 0x1e, 0x7d, 0x59, 0xd0, 0xa5, 0x4c, 0x9e,
	0x79, 0x21, 0xd9, 0x1f, 0xae, 0x01, 0x38, 0x52, 0x65, 0xaa, 0x94, 0xbf, 0x54, 0xcd, 0xd3, 0x60,
	0x5b, 0xa5, 0xb4, 0x6e, 0xe1, 0x4b, 0xb0, 0x99, 0x10, 0x5c, 0x54, 0x9e, 0x1e, 0x35, 0x80, 0x6f,
	0x01, 0x0e, 0x99, 0xca, 0x6a, 0x97, 0x4e, 0xe5, 0xe2, 0xe9, 0x8b, 0x91, 0x91, 0xe0, 0x98, 0x99,
	0x9f, 0x2e, 0x0e, 0xb4, 0xd6, 0x0b, 0x63, 0x41, 0x28, 0xdd, 0x45, 0xf1, 0x26, 0xd5, 0x16, 0x08,
	0xfa, 0x06, 0x13, 0x42, 0xe3, 0x70, 0x89, 0xda, 0xcd, 0x65, 0x3a, 0x27, 0xd3, 0xc5, 0x36, 0x5d,
	0xa1, 0x0e, 0xbe, 0x80, 0x9e, 0xbe, 0x24, 0xd1, 0x8a, 0xac, 0xd3, 0x04, 0xd9, 0x4d, 0x65, 0x1e,
	0xd2, 0xd9, 0x73, 0x48, 0x09, 0x72, 0xf6, 0x4e, 0xf5, 0xe7, 0x1f, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x3c, 0xb1, 0x43, 0x08, 0x02, 0x00, 0x00,
}
